---
title: "Size data analysis"
output: github_document
---

```{r setup, include=FALSE}
library(dplyr)
library(BBSsize)
library(drake)
library(ggplot2)
```

```{r load an ibd}

loadd(ibd_isd_bbs_rtrg_1_4)

```

```{r summarize s and b}

colnames(ibd_isd_bbs_rtrg_1_4)

size_ts <- ibd_isd_bbs_rtrg_1_4 %>%
  group_by(year, id) %>%
  summarize(mass = sum(ind_size)) %>%
  ungroup() %>%
  tidyr::pivot_wider(id_cols = year, names_from = id, values_from = mass, values_fill = 0)

energy_ts <-ibd_isd_bbs_rtrg_1_4 %>%
  group_by(year, id) %>%
  summarize(energy = sum(ind_b)) %>%
  ungroup() %>%
  tidyr::pivot_wider(id_cols = year, names_from = id, values_from = energy, values_fill = 0)

```

```{r load a dataset and do a swap}

loadd(bbs_rtrg_1_4)

size_bbs_rtrg_1_4 <- bbs_rtrg_1_4
size_bbs_rtrg_1_4$abundance <-tibble(dplyr::select(size_ts, - year))
size_bbs_rtrg_1_4$metadata$currency <- "mass"


energy_bbs_rtrg_1_4 <- bbs_rtrg_1_4
energy_bbs_rtrg_1_4$abundance <-tibble(dplyr::select(energy_ts, - year))
energy_bbs_rtrg_1_4$metadata$currency <- "energy"


```


