---
title: "Size data analysis"
output: github_document
---

```{r setup, include=FALSE}
library(dplyr)
library(ggplot2)
```

```{r load data}

sp_raw <- read.csv(here::here("analysis", "species_data", "species_list_working.csv"), stringsAsFactors = F, strip.white = T, na.strings = "")

```

### Data cleanup

Trivial:

- remove common names columns (special characters get messed up in Excel)
- rename `species_id` column (got messed up in excel)


Some substance:

- For species that have been split, fill in values

```{r cleanup, echo = T}

colnames(sp_raw)[1] <- "species_id"

sp_clean <- sp_raw %>%
  select(-english_common_name, -french_common_name, -spanish_common_name, -sporder, -family) 

name_change <- filter(sp_clean, not_in_dunning == 1)

sp_clean <- filter(sp_clean, is.na(not_in_dunning)) %>%
  mutate(added_flag = NA)

for(i in 1:nrow(name_change)) {
    
  if(!is.na(name_change$close_subspecies[i])) {
  matched_rows <- filter(sp_clean,
                         genus == name_change$close_genus[i],
                         species == name_change$close_species[i],
                         subspecies == name_change$close_subspecies[i])
  } else {
    matched_rows <- filter(sp_clean,
                         genus == name_change$close_genus[i],
                         species == name_change$close_species[i])
  }
  
  sp_to_add <- matched_rows %>%
    mutate(species_id = name_change$species_id[i],
           id = name_change$id[i],
           added_flag = 1)
  
  sp_clean <- bind_rows(sp_clean, sp_to_add)
  
}

```


### SD fit

```{r fit sd}

sp_for_sd <- filter(sp_raw,
                    !is.na(sd)) %>%
  mutate(mass = as.numeric(mass),
         sd = as.numeric(sd)) %>%
  mutate(var = sd^2) %>%
  mutate(log_m = log(mass),
         log_var = log(var))


sd_fit <- lm(sp_for_sd, formula = log_var ~ log_m)

summary(sd_fit)

sp_for_sd <- mutate(sp_for_sd,
                    log_var_est = -5.273 + (log_m * 1.995)) %>%
  mutate(var_est = exp(log_var_est))


ggplot(sp_for_sd, aes(x = log_m, y = log_var)) +
  geom_point(alpha = .4) +
  theme_bw() +
  geom_line(aes(x = log_m, y = log_var_est))


ggplot(sp_for_sd, aes(x = mass, y = var)) +
  geom_point(alpha = .4) +
  theme_bw() +
  geom_line(aes(x = mass, y = var_est))


```
